# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vlytvyne <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/29 17:24:54 by vlytvyne          #+#    #+#              #
#    Updated: 2018/11/29 17:24:56 by vlytvyne         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = vlytvyne.filler

all: $(NAME)

$(NAME):
	gcc main.c -o $(NAME) libft.a

clean:

fclean:
	rm -rf $(NAME)

re: fclean all